version: '3.7'
services:
  api:
    build: .
    image: api
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./gcs-sa.json:/gcs-sa.json
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      GOOGLE_APPLICATION_CREDENTIALS: /gcs-sa.json

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres-data:
